# Generated by Django 5.0.6 on 2024-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_series_book_series_number_book_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='../default_profile_xwtjlx', upload_to='covers/'),
        ),
    ]
