# Generated by Django 5.0.6 on 2024-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='../nocover_dhpojf', upload_to='covers/'),
        ),
    ]
