# Generated by Django 3.2.25 on 2024-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('profiles', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('profile', 'book')},
        ),
    ]
