# Generated by Django 3.2.25 on 2024-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('books', '0001_initial'),
        ('reviews', '0002_auto_20240531_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='profile',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'book')},
        ),
    ]
