# Generated by Django 3.2.25 on 2024-05-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reviews', '0003_auto_20240531_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
